on: pull_request
name: Check for missing migrations

jobs:
  missing-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Log into Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Pull base images
        run: docker compose pull
      - name: Create shared network
        run: docker network create mlp_network

      - name: check for missing migrations
        run: docker compose run -T backend poetry run python manage.py makemigrations --check
