version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - scripts/ci-start.sh
  build:
    commands:
      - docker-compose exec -T backend python manage.py wait_for_db
      - docker-compose exec -T backend bandit -r . -ll -iii -c tests/.banditrc
  post_build:
    commands:
      - docker-compose down -t 0
