FROM python:latest

RUN mkdir /code
WORKDIR /code

ADD requirements.txt /code/
ADD requirements.dev.txt /code/
RUN pip install -r requirements.dev.txt

CMD ./manage.py wait_for_db && ./manage.py migrate && ./manage.py createcachetable && uvicorn --host 0.0.0.0 --port 3001 --reload backend.asgi:application
