name: Publish Package

'on':
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Set credentials
        env:
          API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry config pypi-token.pypi "$API_TOKEN"
      - name: Build
        run: poetry build
      - name: Publish
        run: poetry publish
