on:
  schedule:
    - cron: '0 0 1 * * '

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: MetLifeLegalPlans/update-poetry-dependencies@v1
        with:
          latest: true
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
