name: Test Output

'on': pull_request

jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Append path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          pip install --user .
      - name: Create new zygoat project
        run: zg new test
      - name: Backend linting
        run: docker-compose run --rm -T backend poetry run flake8
      - name: Frontend linting
        run: docker-compose run --rm -T frontend yarn lint
